In [48]:
import pandas as pd
import numpy as np
import scipy.stats as st
schiedsrichter = pd.read_csv(r"Schiedsrichter_Lebenserwartung-2.txt",sep=" ", header=None)
schiedsrichter.columns=['Alter', 'lebendig', 'Lebenserwartung']

In [49]:
schiedsrichter.head()

Alter  lebendig  Lebenserwartung
0     63         0               70
1     69         0               71
2     58         0               71
3     61         1               70
4     70         0               70

In [51]:
schiedsrichter["lebendig"].size

227

In [61]:
ref_a = schiedsrichter[schiedsrichter["lebendig"] == 1]
ref_d = schiedsrichter[schiedsrichter["lebendig"] == 0]
ref_d["lebendig"].size

195

In [68]:
print(ref_d.head())
print(ref_d["lebendig"].size)

   Alter  lebendig  Lebenserwartung
0     63         0               70
1     69         0               71
2     58         0               71
4     70         0               70
5     68         0               69
195


In [109]:
ttest = st.ttest_rel(ref_d["Lebenserwartung"].dropna(), ref_d["Alter"].dropna())
# nullhypothese wird nicht verworfen
print(ttest)

Ttest_relResult(statistic=0.9870367754367101, pvalue=0.324854036739876)


In [74]:
ttest.pvalue / 2
# einseitiger test - deshalb wird es nicht verworfen

0.162427018369938

In [105]:
# Teststatistikumsetzung
differenz_lebenserwartung = ref_d["Alter"]-ref_d["Lebenserwartung"]
(differenz_lebenserwartung.mean())/(differenz_lebenserwartung.std()/np.sqrt(ref_d["Lebenserwartung"].size))

-0.98703677543671

In [207]:
print(st.t.ppf(q=0.01, df=differenz_lebenserwartung.size-1, loc=differenz_lebenserwartung.mean(), scale=differenz_lebenserwartung.std()/np.sqrt(differenz_lebenserwartung.size)))
print(st.t.ppf(q=1, df=differenz_lebenserwartung.size-1, loc=differenz_lebenserwartung.mean(), scale=differenz_lebenserwartung.std()/np.sqrt(differenz_lebenserwartung.size)))

-1.8181317009453002
inf


In [121]:
st.wilcoxon(differenz_lebenserwartung, zero_method='wilcox', alternative="greater")

WilcoxonResult(statistic=8640.0, pvalue=0.3295613788219288)

In [126]:
1-st.binom_test(n=differenz_lebenserwartung.size, x=np.sum((differenz_lebenserwartung>0).astype(int)), p=0.5)

0.22537666782261145

In [31]:
ref_d["Lebenserwartung"].mean()

69.01538461538462

In [33]:
ref_d["Alter"].mean()

68.47692307692307

In [41]:
ref_d[ref_d["Lebenserwartung"].dropna() > ref_d["Alter"].dropna()].size

246

In [213]:
(-1.8181317009453002+differenz_lebenserwartung.mean())*differenz_lebenserwartung.std()


-17.952431848914717

In [120]:
(ref_a["Alter"].std()/np.sqrt(ref_a["Alter"].size))/ref_a["Alter"].mean()

0.016857816590150322

In [151]:
print(st.binom.cdf(k=3, n=13, p=0.5))
print(st.binom.cdf(k=9, n=13, p=0.5))

0.046142578125000014
0.953857421875


In [148]:
st.binom.ppf(q=[0.025, 0.975], n=13, p=0.5)

array([ 3., 10.])

In [152]:
import pandas as pd
import numpy as np
import scipy.stats as st
schiedsrichter = pd.read_csv(r"Schiedsrichter_Lebenserwartung-2.txt",sep=" ", header=None)
schiedsrichter.columns=['Alter', 'lebendig', 'Lebenserwartung']

In [156]:
ref_d =  schiedsrichter[schiedsrichter["lebendig"] == 0]
ref_d["lebendig"].size

195

In [177]:
altersdifferenz = ref_d["Lebenserwartung"] - ref_d["Alter"]

In [187]:
st.t.ppf(q=[0.01], loc=0, scale=altersdifferenz.std()/np.sqrt(altersdifferenz.size), df=altersdifferenz.size-1)

array([-1.27967016])

In [179]:
altersdifferenz.mean()

0.5384615384615384

In [264]:
wert = altersdifferenz.mean() + st.t.ppf(q=[0.99, 0.01], df=altersdifferenz.size-1)*altersdifferenz.std()/np.sqrt(altersdifferenz.size)
print(wert)
wert = -1*altersdifferenz.mean() - st.t.ppf(q=[0.99,0.01], df=altersdifferenz.size-1)*altersdifferenz.std()/np.sqrt(altersdifferenz.size)
print(wert)

[ 1.8181317  -0.74120862]
[-1.8181317   0.74120862]


In [181]:
st.wilcoxon(altersdifferenz, correction=True).pvalue/2

0.32981607141904357

In [182]:
(altersdifferenz.std()/np.sqrt(altersdifferenz.size))/altersdifferenz.mean()

1.013133476771982

In [183]:
ref_a = schiedsrichter[schiedsrichter["lebendig"] == 1]

In [185]:
ref_a["Alter"].mean()

59.125

In [186]:
(ref_a["Alter"].std()/np.sqrt(ref_a["Alter"].size))/ref_a["Alter"].mean()

0.016857816590150322

In [191]:
-1.8181317009452997*(altersdifferenz.std()/np.sqrt(altersdifferenz.size))

-0.9918515876812679

In [214]:
print(st.t.ppf(q=[0.99], df=altersdifferenz.size-1))


[2.34572281]


In [197]:
st.t.cdf(x=[-1.8181317009452997, 0.74120862402222298], df=194)

array([0.03529319, 0.77026839])

In [205]:
st.t.ppf(q=0.05, loc=0, scale=6.2/np.sqrt(9), df=8)

-3.8430659442138757

In [223]:
help(st.ttest_1samp)

Help on function ttest_1samp in module scipy.stats.stats:

ttest_1samp(a, popmean, axis=0, nan_policy='propagate')
    Calculate the T-test for the mean of ONE group of scores.
    
    This is a two-sided test for the null hypothesis that the expected value
    (mean) of a sample of independent observations `a` is equal to the given
    population mean, `popmean`.
    
    Parameters
    ----------
    a : array_like
        sample observation
    popmean : float or array_like
        expected value in null hypothesis. If array_like, then it must have the
        same shape as `a` excluding the axis dimension
    axis : int or None, optional
        Axis along which to compute test. If None, compute over the whole
        array `a`.
    nan_policy : {'propagate', 'raise', 'omit'}, optional
        Defines how to handle when input contains nan. 'propagate' returns nan,
        'raise' throws an error, 'omit' performs the calculations ignoring nan
        values. Default is 'propagate'.