In [1]:
import matplotlib.pyplot as plt
import scipy.stats as st
import seaborn as sns
import pandas as pd
from scipy.stats import norm, uniform, expon, t
from scipy.integrate import quad
from sympy.solvers import solve
from sympy import Symbol
import numpy as np
from pandas import Series, DataFrame

In [2]:
fuellungen = Series([71, 69, 67, 68, 73, 72, 71, 71, 68, 72, 69, 72])

In [3]:
fuellungen.mean()

70.25

In [4]:
fuellungen_standardisiert = fuellungen

In [13]:
norm.ppf(q=[0.05,0.95], loc=70, scale=1.5/np.sqrt(12))

array([69.28775749, 70.71224251])

In [15]:
np.sqrt(12)*((70.25-70)/1.5)

0.5773502691896257

In [17]:
norm.ppf(q=0.05)

-1.6448536269514729

# 6.2

In [18]:
fuellungen2 = Series([71, 69, 67, 68, 73, 72, 71, 71, 68, 72, 69, 72])

In [19]:
fuellungen.mean()

70.25

In [25]:
t.ppf(q=[0.05], df=fuellungen2.size-1, loc=70, scale=fuellungen2.std()/np.sqrt(fuellungen2.size))

array([68.98397389])

1.9598237397554634

# 6.3

In [34]:
norm.ppf(q=[0.95], loc=200, scale=10/np.sqrt(16))

array([204.11213407])

In [36]:
norm.cdf(x=205, loc=200, scale=10/np.sqrt(16))

0.9772498680518208

In [37]:
norm.cdf(x=200, loc=200, scale=10/np.sqrt(16))

0.5

In [30]:
t.ppf(q=[0.95], df=16-1, loc=200, scale=10/np.sqrt(16))

array([204.38262589])

In [31]:
t.cdf(x=200, loc=200, df=16-1, scale=10/np.sqrt(16))

0.5

In [ ]:
st.ttest_1samp()